name: Pytest & flake8 control Push
on: [push, pull_request]
jobs:
    qa:
      name: Check tests
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout on master
          uses: actions/checkout@v3

        - name: Set up Python environment
          uses: actions/setup-python@master
          with:
            python-version: "3.10"

        - name: Install pytest and flake8
          run: |
            pip install pytest
            pip install flake8
            python -m pip install flake8-github-actions
        - name: Run tests
          run: |
            pytest

        - name: Run flake8 Lint
          # run: |
          #   # fail if there are any flake8 errors
          #   flake8 . --count --max-complexity=15 --max-line-length=127 --statistics
          uses: py-actions/flake8@v2
          with:
            max-line-length: "100"
            path: "tests"
            plugins: "flake8-bugbear==22.1.11 flake8-black"